name: Cucumber Tests

on:
  push:
    branches: [main, cucumber-report-host]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Cucumber tests
        run: npm run test:cucumber:no-open
        continue-on-error: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create _site directory
        run: |
          mkdir -p _site
          cp -r reports/* _site/
          echo '<meta http-equiv="refresh" content="0; url=cucumber-report.html">' > _site/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
